# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER aha

# 挂载目录
VOLUME /home/aha
# 创建目录
RUN mkdir -p /home/aha
# 指定路径
WORKDIR /home/aha
# 复制jar文件到路径
COPY ./jar/aha-visual-monitor.jar /home/aha/aha-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","aha-visual-monitor.jar"]
